repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.70.0 # Use the latest version from the repository
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
