AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  AWSAccountId:
    Type: String
  ProjectName:
    Type: String
  Stage:
    Type: String

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ProjectName}-bucket-${AWSAccountId}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: "DeleteOldObjects"
            Status: "Enabled"
            ExpirationInDays: 30

  AddPartitionFunction:
    Type: AWS::Serverless::Function
    Properties: 
      FunctionName: !Sub "${ProjectName}-${Stage}-add-partition"
      Handler: src/lambda/add_partition.main.lambda_handler
      Runtime: python3.11
      MemorySize: 2048
      Timeout: 900
      Role: !Sub "arn:aws:iam::${AWSAccountId}:role/${ProjectName}/add-partition/${ProjectName}-add-partition-lambda-role"
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref MyS3Bucket
        - PolicyName: AthenaAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:ListDatabases
                  - athena:ListTableMetadata
                  - athena:ListQueryExecutions
                Resource: "*"
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Ref AWSAccountId
      Events:
        S3PutEvent:
          Type: S3
          Properties:
            Bucket: !Ref MyS3Bucket
            Events: s3:ObjectCreated:Put
